# nixpacks.toml

[phases.setup]
# Remove "..." to stop default collisions
# Just ask for python and ffmpeg. 
# We control the python version via the ENVIRONMENT VARIABLE.
nixPkgs = ["python", "ffmpeg"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "celery -A celery_init worker --loglevel=info --concurrency=2"
