# nixpacks.toml

[phases.setup]
# We specify python311 which definitely includes pip
nixPkgs = ["python311", "ffmpeg", "gcc", "zlib"]

[phases.install]
# Nixpacks puts python in a weird place sometimes.
# We force it to create a virtual environment first.
cmds = [
    "python3.11 -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
# We must activate the venv before running celery
cmd = ". /opt/venv/bin/activate && celery -A celery_init worker --loglevel=info --concurrency=2"
