# nixpacks.toml
[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "celery -A celery_init worker --loglevel=info --concurrency=2"
